config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :contacts, only: :create
  root to: 'pages#home'
  resources :looks
  resources :products

  get "contact", to: "pages#contact"
  get "qui-sommes-nous", to: "pages#nous"
  get "boutique", to: "pages#boutique"
  get "partenaires", to: "pages#partenaires"
  get "faq", to: "pages#faq"
  get "mentionslegales", to: "pages#mentionslegales"
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products, dependent: :destroy
  belongs_to :look
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :user
  belongs_to :look
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name ,presence: true
  validates :subject ,presence: true
  validates :email ,presence: true
  validates :message ,presence: true
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :imports, dependent: :destroy
  enum type: [:csv, :xml ]
end

app/models/import.rb
class Import < ActiveRecord::Base
  belongs_to :feed
  enum status: [:success, :pending, :error]
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/look.rb
class Look < ActiveRecord::Base
  has_many :choices, dependent: :destroy
  has_many :brands, dependent: :destroy
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :product

  validates :price, presence: true
  validates :product, presence: true
  validates :supplier, presence: true

include PgSearch

  pg_search_scope :search_engine_size, against: [ :size ]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :likes, dependent: :destroy
  has_many :offers, dependent: :destroy
  belongs_to :brand
  validates_uniqueness_of :ean

  include PgSearch

  def size_array
    self.size.split(',')
  end

  def title_short
    self.title.split(":")[0] unless self.title.nil?
  end

  def best_offer
    self.offers.min_by{ |offer| offer.price }
  end

  pg_search_scope :search_engine, against: [ :title, :description, :color, :category ]


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #
  #
  #
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :choices, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def default_url_options
  { host: ENV['HOST'] || 'localhost:3000' }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_param)
    @contact.save
    ContactMailer.contact(@contact).deliver_now
    redirect_to root_path, notice: 'Nous avons bien reçu votre demande de contact.'
  end

  private
  def contact_param
    params.require(:contact).permit(:name, :subject, :email, :message)
  end
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController

  def index
    search_params = session['search_params']

    @looks_selected = []

    unless search_params.nil?
      @looks_selected = search_params['looks'].reject{|k,v| v == "0"}.keys if search_params['looks']
    end

    @looks = Look.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def contact
    @contact = Contact.new
  end

  def nous
  end

  def partenaires
    @contact = Contact.new
  end

  def faq
    @contact = Contact.new
  end

  def mentionslegales
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
  end

  def index
    # params[:looks] = {'20' => '1'} if params[:looks].blank? or \
    # (params[:looks].include? '20' and params[:looks]['20'] == '1')
    session['search_params'] = params

    query = params[:query]
    category = params[:category]
    size = params[:size]
    color = params[:color]

    @looks = params[:looks] || []

    if @looks.length == 0
      products_from_brand = Product.includes(:brand).all
      @looks_name = ["-"]
    else
      looks = @looks.reject{|k,v| v == '0'}.keys
      @looks_name = looks.map { |k,v| Look.find(k).name }
      brands = Brand.includes(:look).where(look: looks)
      products_from_brand = Product.includes(:brand).where(brand: brands)
    end

    # if looks.include? '20'
    #   # Tous les looks
    #   @looks_name = [Look.find(20).name]
    #   products_from_brand = Product.includes(:brand).all
    # else
    #   @looks_name = looks.map { |k,v| Look.find(k).name }
    #   brands = Brand.includes(:look).where(look: looks)
    #   products_from_brand = Product.includes(:brand).where(brand: brands)
    # end

    products = products_from_brand

    products = products.where(category: category) unless category.blank?
    products = products.where(color: color) unless color.blank?
    unless size.blank?
      product_ids = Offer.search_engine_size(size).map(&:product_id)
      products = products.where(id: product_ids)
    end

    unless query.blank?
      products = products.search_engine(query)
    end

    @products = products.page(params[:page]).per(30)
    @total = @products.try(:total_count)
    @categories = Product.where(id: products_from_brand.map(&:id)).select(:category).map(&:category).uniq || []
    @colors = Product.where(id: products_from_brand.map(&:id)).select(:color).map(&:color).uniq || []
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<h1>Contacts#new</h1>
<p>Find me in app/views/contacts/new.html.erb</p>

app/views/looks/index.html.erb
<div class="padded">
  <%= form_tag products_path, method: :get do %>
      <h3 class="text-center">
        Laissez-vous guider parmi nos <span class="number"><%= Product.count %></span> références en sélectionnant un ou plusieurs looks
      </h3>

      <div class="container">
        <div class="row">
          <% Look.all.each do |look| %>
              <div class="col-xs-12 col-sm-4 col-md-3">
                <div class="card-look" >
                  <div class="card-name"><%= look.name %> </div>
                  <div class="card-filter" style="background-image: url('<%= image_path look.photo %>') ">
                  </div>
                  <div class="card-hover hide">
                    <!--     <p>Je suis une super look qui déchire </p> -->
                    <p><span><%= look.description %></span></p>
                  </div>
                  <div class="card-check <%= 'hide' unless @looks_selected.include?(look.id.to_s) %>">
                    <i class="fa fa-check"></i>
                  </div>
                  <input type="hidden" name="looks[<%= look.id.to_s %>]" value="<%= @looks_selected.include?(look.id.to_s) ? '1' : '0' %>">
                </div>
              </div>
          <%end %>
        </div>
      </div>

      <div class="text-center">
        <input type="submit" value="Je découvre" class="btn navbar-wagon-button looks-cta">
      </div>

  <% end %>

</div>


<% content_for :after_js do %>
    <script>
      $(function(){
        $('.card-look').click(function() {
          $(this).children(".card-check").toggleClass('hide');
          var el = $(this).children('input[type=hidden]');
          el.val(el.val() == 0 ? 1 : 0);
        });

        $(".card-look").on("mouseover", function() {
          $(this).children(".card-hover").removeClass('hide');
        })

        $(".card-look").on("mouseout", function() {
          $(this).children(".card-hover").addClass('hide');
        })

      });
    </script>
<% end %>

app/views/products/index.html.erb
<h1 class="text-center">Voici les articles de votre look préféré :</h1>
  <h5 class="text-center">Affichage de <%= @products.length %> articles sur <%= @total %> trouvés</h5>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <form method="get">
        <h4>Vos looks</h4>
        <% @looks_name.each do |l| %>
        <h5><strong><%= l %></strong></h5>
        <% end %>
        <p>
        <%= link_to looks_path, style: "font-size: 12px" do %>
        <div class="change"><em>Changer de look</em></div>
        <% end %>
        </p>

        <% @looks.each do |key,value| %>
          <%= hidden_field_tag "looks[#{key}]", value %>
        <% end %>
        <%= hidden_field_tag "query", params[:query] %>
        <hr>
        <h4>Categories</h4>
        <select name="category" style="width: 100%" class="form-control">
          <option value=""></option>
          <% @categories.each do |category| %>
            <option value="<%= category %>" <%= 'selected="selected"' if category == params[:category] %>><%= category.capitalize %></option>
          <% end %>
        </select>
        <hr>
        <h4>Couleurs</h4>
        <select name="color" style="width: 100%" class="form-control">
          <option value=""></option>
          <% @colors.each do |color| %>
            <option value="<%= color %>" <%= 'selected="selected"' if color == params[:color] %>><%= color.capitalize %></option>
          <% end %>
        </select>
        <hr>
        <h4>Tailles</h4>
        <select name="size" style="width: 100%" class="form-control">
          <option value=""></option>
          <% %w{S M L XL XXL XXXL}.each do |s| %>
              <option value="<%= s %>" <%= 'selected="selected"' if s == params[:size] %>><%= s %></option>
          <% end %>
        </select>
      </form>
    </div>
    <div class="col-md-9">
      <% @products.each do |p| %>
          <div class="col-xs-12 col-md-4">
            <div class="card-product">
              <%= image_tag p.image%>
              <div class="card-title">
                <%= p.title_short %>
              </div>
              <div class="card-price">
                <p><%= p.offers.first.price %>€</p>
              </div>
              <%= link_to product_path(p), class: 'card-detail'  do %>
                  <i class='fa fa-info-circle'> </i>
              <% end %>
              <%= link_to "Voir l'offre chez #{p.best_offer.supplier}", p.best_offer.link,  class: 'btn  btn-danger btn-block card-cta', target: 'blank'%>
            </div>
          </div>
      <% end %>
      <h4 class="text-center"><%= paginate @products %></h4>
     </div>
      <% if @products.length > 0 %>
        <div class="row">
          <div class="text-center">
            <p><%= link_to 'Choisir un autre look', looks_path, :class => 'btn btn-danger' %>
              <%= link_to 'Voir tous les produits', products_path, :class => 'btn btn-danger' %>
            </p>
          </div>
        </div>
      <% end %>
        </div>
</div>

<% content_for :after_js do %>
    <script>
      $('select').on('change', function() {
        $(this).siblings('select').val('');
        $(this).parent('form').submit();
      });
    </script>
<% end %>

app/views/products/show.html.erb
<div class="padded">
  <%= link_to " Retour", products_path, :class => "btn btn-danger text-right" %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="border-gray text-center ">
            <%= image_tag @product.image, class: "full" %>
        </div>
      </div>
        <div class="col-xs-12 col-md-6">
            <h2><%= @product.title %></h2>
            <p><%= @product.description %></p>
            <% @product.offers.each do |offer|%>
            <p>Prix : <%= offer.price %>€</p>
            <p>Tailles disponibles : <%= offer.size %> </p>
            <% end %>
            <%= link_to "VOIR L'OFFRE CHEZ LE PARTENAIRE", @product.best_offer.link, target: "blank", :class => "btn btn-danger" %>
        </div>
    </div>
  </div>
</div>