config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :contacts, only: :create
  root to: 'pages#home'
  resources :looks
  resources :products

  get "contact", to: "pages#contact"
  get "qui-sommes-nous", to: "pages#nous"
  get "boutique", to: "pages#boutique"
  get "partenaires", to: "pages#partenaires"
  get "faq", to: "pages#faq"
  get "mentionslegales", to: "pages#mentionslegales"
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products, dependent: :destroy
  belongs_to :look
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :user
  belongs_to :look
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name ,presence: true
  validates :subject ,presence: true
  validates :email ,presence: true
  validates :message ,presence: true
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :imports, dependent: :destroy
  enum type: [:csv, :xml ]
end

app/models/import.rb
class Import < ActiveRecord::Base
  belongs_to :feed
  enum status: [:success, :pending, :error]
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/look.rb
class Look < ActiveRecord::Base
  has_many :choices, dependent: :destroy
  has_many :brands, dependent: :destroy
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :product

  validates :price, presence: true
  validates :product, presence: true
  validates :supplier, presence: true

include PgSearch

  pg_search_scope :search_engine_size, against: [ :size ]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :likes, dependent: :destroy
  has_many :offers, dependent: :destroy
  belongs_to :brand
  validates_uniqueness_of :ean

  include PgSearch

  def size_array
    self.size.split(',')
  end

  def title_short
    self.title.split(":")[0] unless self.title.nil?
  end

  def best_offer
    self.offers.min_by{ |offer| offer.price }
  end

  pg_search_scope :search_engine, against: [ :title, :description, :color, :category ]


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #
  #
  #
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :choices, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def default_url_options
  { host: ENV['HOST'] || 'localhost:3000' }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_param)
    @contact.save
    ContactMailer.contact(@contact).deliver_now
    redirect_to root_path, notice: 'Nous avons bien reçu votre demande de contact.'
  end

  private
  def contact_param
    params.require(:contact).permit(:name, :subject, :email, :message)
  end
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController

  def index
    search_params = session['search_params']

    @looks_selected = []

    unless search_params.nil?
      @looks_selected = search_params['looks'].reject{|k,v| v == "0"}.keys if search_params['looks']
    end

    @looks = Look.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def contact
    @contact = Contact.new
  end

  def nous
  end

  def partenaires
    @contact = Contact.new
  end

  def faq
    @contact = Contact.new
  end

  def mentionslegales
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
  end

  def index
    # params[:looks] = {'20' => '1'} if params[:looks].blank? or \
    # (params[:looks].include? '20' and params[:looks]['20'] == '1')
    session['search_params'] = params

    query = params[:query]
    category = params[:category]
    size = params[:size]
    color = params[:color]

    @looks = params[:looks] || []

    if @looks.length == 0
      products_from_brand = Product.includes(:brand).all
      @looks_name = ["-"]
    else
      looks = @looks.reject{|k,v| v == '0'}.keys
      @looks_name = looks.map { |k,v| Look.find(k).name }
      brands = Brand.includes(:look).where(look: looks)
      products_from_brand = Product.includes(:brand).where(brand: brands)
    end

    # if looks.include? '20'
    #   # Tous les looks
    #   @looks_name = [Look.find(20).name]
    #   products_from_brand = Product.includes(:brand).all
    # else
    #   @looks_name = looks.map { |k,v| Look.find(k).name }
    #   brands = Brand.includes(:look).where(look: looks)
    #   products_from_brand = Product.includes(:brand).where(brand: brands)
    # end

    products = products_from_brand

    products = products.where(category: category) unless category.blank?
    products = products.where(color: color) unless color.blank?
    unless size.blank?
      product_ids = Offer.search_engine_size(size).map(&:product_id)
      products = products.where(id: product_ids)
    end

    unless query.blank?
      products = products.search_engine(query)
    end

    @products = products.page(params[:page]).per(30)
    @total = @products.try(:total_count)
    @categories = Product.where(id: products_from_brand.map(&:id)).select(:category).map(&:category).uniq || []
    @colors = Product.where(id: products_from_brand.map(&:id)).select(:color).map(&:color).uniq || []
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/pages/boutique.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "baskets-hugo-boss.jpg"%>
      <div class="carousel-caption">
        <h2>Découvrez les dernières baskets Hugo Boss !</h2>
        <p><%= link_to "Voir toutes les baskets", products_path, class: "btn navbar-wagon-button cta btn-lg margin-sm" %></p>
      </div>
    </div>
      <div class="item">
        <%= image_tag "costume-homme.jpg"%>
       <div class="carousel-caption">
        <h2>C'est parti pour la saison des mariages !.</h2>
        <p><%= link_to "Voir tous les costumes", products_path, class: "btn navbar-wagon-button cta btn-lg margin-sm" %></p>
        </div>
      </div>
    <div class="item">
    <%= image_tag "slide4.jpg"%>
      <div class="carousel-caption">
        <h2>Recevez des conseils personnalisés d'experts de la mode.</h2>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="wrapper-feature text-center">
  <div class="container">
    <div class="row">
    <h2>Chez Monsieur Mode Shop, on a le sens du service</h2>
      <div class="col-xs-12 col-sm-4">
        <div class="feature">
          <%= image_tag "livraison-gratuite.png", class: "text-center"%>
          <div><p>Nos partenaires proposent la livraison gratuite avec ou sans code promo !</p></div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="feature">
          <%= image_tag "paiement-securise.png", class: "text-center"%>
          <div><p>Paiement 100% sécurisé chez des acteurs de confiance du web français !</p></div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="feature">
          <%= image_tag "retour-gratuit.png", class: "text-center"%>
          <div><p>Les retours sont gratuits au moins 1 fois sous 14 à 30 jours !</p></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-contact text-center">
  <div class="container">
    <div class="row"><h2>Gardons contact !</h2>
      <div class="col-xs-12 col-sm-4">
        <div class="feature">
          <div><h3>Contactez Monsieur Mode</h3>
          <p>Nos stylistes sont à votre disposition<br>du lundi au vendredi de 9h à 20h00<br> et le samedi de 10h à 18h</p>
          <%= link_to "J'envoie un email", contact_path, class: "btn navbar-wagon-button cta btn-lg margin-sm" %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="feature"><h3>Newsletter</h3>
        <p>Recevez toute l'actualité de la mode masculine, nos offres exclusives et des codes promos en vous abonnant !</p>
             <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
  #mc_embed_signup{ clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
  /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//herokuapp.us13.list-manage.com/subscribe/post?u=633fc60c253da38c19cda95b2&amp;id=f9d925250a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">

  <input type="email" value="" name="EMAIL" class="email text-center" id="mce-EMAIL" placeholder="Votre email" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_633fc60c253da38c19cda95b2_f9d925250a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Je m'inscris" name="subscribe" id="mc-embedded-subscribe" class="navbar-wagon-item navbar-wagon-button btn"></div>
    </div>
</form>
</div>
</div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="feature"><h3>Suivez nous !</h3>
        <div><p>Rejoignez la communauté, soyez informé des derniers bons plans avant les autres et partagez vos avis sur nos réseaux sociaux !</p></div>
          <div class="share-links text-center">
    <a href="https://www.facebook.com/Monsieur-Mode-Shop-La-Boutique-Homme-497697997101649" class="facebook">
      <i class="fa fa-facebook"></i>
    </a>
    <a href="https://twitter.com/monsieurmode" class="reseaux">
      <i class="fa fa-twitter"></i>
    </a>
    <a href="https://fr.pinterest.com/monsieurmode" class="reseaux">
      <i class="fa fa-pinterest"></i>
    </a>
    <a href="https://www.linkedin.com/in/monsieur-mode-b8a3b355" class="reseaux">
      <i class="fa fa-linkedin"></i>
    </a>
  </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
   <!-- BANNER HOME -->

<div class="banner banner-home"data-stellar-background-ratio="0.5">
  <div class="banner-filter">
  </div>
    <div class="banner-content text-center">
    <h1> Le shop de Monsieur Mode </h1>
    <p class="tagline"> Trouvez votre look pour homme en 1 clic </p>
    <%= link_to "Je choisis mon look", looks_path, class: "btn navbar-wagon-button cta btn-lg margin-sm" %>
    </div>
</div>

<div class="wrapper-feature text-center">
  <div class="container">
    <div class="row">
    <h2>Comment ça marche ?</h2>
      <div class="col-xs-12 col-sm-4">
        <div class="feature">
          <%= image_tag "button_ok.png", class: "text-center"%>
          <div><p>1. Choisissez vos looks préférés parmi plusieurs tenues</p></div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="feature">
          <%= image_tag "White-Shirt.png", class: "text-center"%>
          <div><p>2. Découvrez les meilleures tendances pour votre style</p></div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="feature">
          <%= image_tag "carte-de-paiement.png", class: "text-center"%>
          <div><p>3. Achetez directement sur les boutiques de vos marques préférées</p></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="banner banner-parallax banner-parallax1" data-stellar-background-ratio="0.5">
  <div class="banner-filter"></div>
  <div class="banner-content text-center">
    <h1>Toute la mode homme<br>et tous les bons plans sont<br>sur Monsieur Mode Shop !</h1>
    <p>Vos actus mode et les dernières tendances de vêtements et accessoires sont disponibles juste ici !</p>
  </div>
</div>

<div class="wrapper-features padded">
  <div class="features text-center">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <%= image_tag "feature1.png", class: "image-chiffre"%>
          <p class="text-center">Trouvez vos articles préférés parmi</p>
          <h2 class="text-center"><%= Product.count %> références</h2>
        </div>
        <div class="col-xs-12 col-sm-6">
          <%= image_tag "partner-feature.png", class: "image-chiffre"%>
          <p class="text-center">Nous travaillons actuellement avec</p>
          <h2 class="text-center"><%= Feed.count %> partenaires</h2>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
      <div class="item">
        <%= image_tag "costume-homme.jpg"%>
       <div class="carousel-caption">
        <h2>C'est parti pour la saison des mariages !.</h2>
        <p><%= link_to "Voir tous les costumes", products_path, class: "btn navbar-wagon-button cta btn-lg margin-sm" %></p>
        </div>
      </div>
    <div class="item active">
      <%= image_tag "costume-homme.jpg"%>
      <div class="carousel-caption">
        <h2>Profitez des meilleurs prix du web !</h2>
      </div>
    </div>
    <div class="item">
    <%= image_tag "slideA.jpg"%>
      <div class="carousel-caption">
        <h2>Retrouvez une sélection de marques et de créateurs incontournables.</h2>
      </div>
    </div>
    <div class="item">
    <%= image_tag "slide4.jpg"%>
      <div class="carousel-caption">
        <h2>Recevez des conseils personnalisés d'experts de la mode.</h2>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="wrapper-temoignage padded bg-grey text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="record">
          <%= image_tag "visage2.jpg", class: "avatar-bordered-large"%>
          <em>Sylvie de Lyon</em>
        </div>
        <p>"Ce site me fait gagner un temps fou ! Mon mari fait du 3XL. Avant, je consultais des dizaines de boutiques et je ne trouvais pas grand chose. Aujourd'hui, je trouve tout avec Monsieur Mode ! Merci et bonne continuation à votre équipe !"</p>

      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="record">
          <%= image_tag "michael.png", class: "avatar-bordered-large"%>
          <em>Michaël de Marseille</em>
        </div>
        <p>"Top !! Je peux faire des recherches par look mais je peux aussi voir tous les produits disponibles sur la boutique et faire moi même mes tris pour trouver l'article idéal ! C'est vraiment Super Pratique !"</p>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="record">
          <%= image_tag "visage1.jpg", class: "avatar-bordered-large"%>
          <em>Rebecca de Paris</em>
        </div>
        <p>"Bonjour, d'habitude je n'achète que sur Amazon. Je connaissais des moteurs de recherche tels que Google Shopping ou Shopalike, mais là, la navigation est simple, efficace et le choix est complètement dingue !"</p>
      </div>
    </div>
      <div class="container text-center">
        <%= link_to "Je détermine mon look", looks_path, class: "btn navbar-wagon-button cta btn-lg margin-sm" %>
      </div>
  </div>
</div>

<div class="banner banner-parallax banner-parallax2" data-stellar-background-ratio="0.5">
 <div class="banner-filter"> </div>
  <!-- <h1>www.adopteunstyle.com</h1> -->
  <div class="banner-content">
    <div class="newsletter text-center">
     <h2>RESTONS EN CONTACT !</h2>
     <p>Inscrivez-vous à la newsletter pour être tenu informé des dernières actualités</p>
     <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
  #mc_embed_signup{ clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
  /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//herokuapp.us13.list-manage.com/subscribe/post?u=633fc60c253da38c19cda95b2&amp;id=f9d925250a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">

  <input type="email" value="" name="EMAIL" class="email text-center" id="mce-EMAIL" placeholder="Votre email" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_633fc60c253da38c19cda95b2_f9d925250a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Je m'inscris" name="subscribe" id="mc-embedded-subscribe" class="navbar-wagon-item navbar-wagon-button btn"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->

    </div>
  </div>

</div>

<div class="wrapper-form">
  <div class="text-center">
    <p>Une question ? Envoyez nous un message. Réponse garantie sous 24 heures.</p>
  </div>
<div class="container text-center">
  <%= simple_form_for @contact do |f| %>
    <%= f.input :name, placeholder: "Votre Nom", label: false %>
    <%= f.input :email, placeholder: "Votre Email", label: false %>
    <%= f.input :subject, placeholder: "L'objet de votre Message", label: false %>
    <%= f.input :message, placeholder: "Votre Message", label: false, :input_html => {:rows => 5} %>
    <%= f.button :submit, "Je valide mon message", class: "btn navbar-wagon-button cta btn-lg margin-sm" %>
  <% end %>
</div>
</div>
      <!-- <form class="form-horizontal" action="" methode="POST">
          <div class="form-group">
              <div class="col-sm-12">
                <input type="text" class="form-control" id="inputEmail3" placeholder="Your name"" ">
              </div>
            </div>
          <div class="form-group">

              <div class="col-sm-12">
                <input type="text" class="form-control" id="inputEmail3" placeholder="Subject">
              </div>
            </div>
            <div class="form-group">

              <div class="col-sm-12">
                <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
              </div>
            </div>
            <div class="form-group">

              <div class="col-sm-12">
                <textarea type="text" class="form-control" id="inputText" rows="9" placeholder="Contact us !"></textarea>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">
                <button type="submit" class="btn btn-primary">Valider</button>
              </div>
            </div>
          </form>
 -->

app/views/pages/mentionslegales.html.erb
<div class="container text-center">

  <h1>MENTIONS LÉGALES</h1>

  <strong>Propriété :</strong><br><br>

  Le présent site est la propriété de la société « Monsieur Mode ».<br>

  Monsieur Mode est géré et administré par Michaël TURCAN, rédacteur et gérant.<br><br>

  <strong>Siège social :</strong><br><br>

  Société Monsieur Mode Shop<br>

  à l'attention de Michaël TURCAN<br>

  106 Boulevard Barry<br>

  Résidence 13ème Sud<br>

  Bâtiment A1 – Bureau 115<br>

  13013 Marseille<br>

  SIRET : 53751187500016<br>

  <%= link_to "Cliquez ici pour nous contacter", contact_path, class: "btn navbar-wagon-button cta btn-lg margin-sm" %>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="share-links text-center">
    <a href="https://www.facebook.com/Monsieur-Mode-Shop-La-Boutique-Homme-497697997101649" class="share-link">
      <i class="fa fa-facebook"></i>
    </a>
    <a href="https://twitter.com/monsieurmode" class="share-link">
      <i class="fa fa-twitter"></i>
    </a>
    <a href="https://fr.pinterest.com/monsieurmode" class="share-link">
      <i class="fa fa-pinterest"></i>
    </a>
    <a href="https://www.linkedin.com/in/monsieur-mode-b8a3b355" class="share-link">
      <i class="fa fa-linkedin"></i>
    </a>
  </div>
  <div class="row text-center">
    <div class="col-xs-12 col-md-4">
      <h3>Monsieur Mode Shop</h3>
        <ul class="list-unstyled">
          <li><%= link_to "Qui Sommes Nous ?", qui_sommes_nous_path%></li>
          <li><%= link_to "Mentions Légales", mentionslegales_path%></li>
          <li><%= link_to "Accès direct à la boutique", products_path%></li>
          <li><%= link_to "Choisir mon look", looks_path%></li>
          <li><a href="http://www.monsieur-mode.com">Blog Monsieur Mode</a></li>
          <li><%= link_to "FAQ / Foire Aux Questions", faq_path%></li>
          <li><%= link_to "Nous contacter", contact_path%></li>
        </ul>
    </div>
    <div class="col-xs-12 col-md-4">
      <h3>Nos Partenaires</h3>
        <ul class="list-unstyled">
          <li><a href="https://www.affili.net/fr/accueil">Affilinet</a></li>
          <li><a href="http://www.effiliation.com/">Effiliation</a></li>
          <li><a href="https://fr.netaffiliation.com/">Netaffiliation</a></li>
          <li><a href="http://fr.publicidees.com/">Publicidées</a></li>
          <li><a href="http://www.tradedoubler.com/fr/">Tradedoubler</a></li>
          <li><a href="http://zanox.com/fr/">Zanox</a></li>
          <li>
            <%= link_to "Devenir partenaire", partenaires_path%>
          </li>
        </ul>
    </div>
     <div class="col-xs-12 col-md-4">
      <h3>Newsletter</h3>
      <br>
        <ul class="list-unstyled">
          <li>
                <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
  #mc_embed_signup{ clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
  /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//herokuapp.us13.list-manage.com/subscribe/post?u=633fc60c253da38c19cda95b2&amp;id=f9d925250a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">

  <input type="email" value="" name="EMAIL" class="email text-center" id="mce-EMAIL" placeholder="Votre email" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <br><br>
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_633fc60c253da38c19cda95b2_f9d925250a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Je m'inscris" name="subscribe" id="mc-embedded-subscribe" class="navbar-wagon-item navbar-wagon-button btn"></div>
    </div>
</form>
</div>
          </li>
        </ul>
    </div>

  </div>

  </div>
</div>



<div class="mentions-legales">
  <p id="mm-footer" class="text-center">
    © 2016 <a href="http://www.monsieur-mode-shop.com">Monsieur Mode Shop</a>
  </p>
</div>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-21016023-4', 'auto');
  ga('send', 'pageview');

</script>